name: Deploy to AWS EC2

on:  
  push:  
    branches:
      - main  
  pull_request:  
    branches:
      - main

jobs:  
  build-and-test:  
    runs-on: ubuntu-latest  

    steps:  

      - name: Checkout do Código  
        uses: actions/checkout@v4  

      - name: Configurar Node.js
        uses: actions/setup-node@v4  
        with:
          node-version: '18'  

      - name: Instalar Dependências
        run: npm install  

      - name: Executar Testes
        run: npm test  

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} 
          username: ${{ secrets.EC2_USERNAME }} 
          key: ${{ secrets.EC2_SSH_KEY }} 
          script: |
            cd /home/ec2-user/Nest-AWS
            git pull origin main
            npm install
            npm run start
            pm2 restart Nest-AWS || pm2 start dist/main.js --name "Nest-AWS"