name: Deploy to AWS EC2

on:  
  push:  
    branches:
      - main  
  pull_request:  
    branches:
      - main

jobs:  
  build-and-test:  
    runs-on: ubuntu-latest  

    steps:  

      - name: Checkout do Código  
        uses: actions/checkout@v4  

      - name: Configurar Node.js
        uses: actions/setup-node@v4  
        with:
          node-version: '18'  

      - name: Instalar Dependências
        run: npm install  

      - name: Executar Testes
        run: npm test  

      - name: Build
        run: npm run build

      - name: Copy files with SSH
        uses: easingthemes/ssh-deploy@main
        env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ${{ secrets.EC2_USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}
        EXCLUDE: "/dist/, /node_modules/, **.env, rebuild_app.sh, watcher.sh"